
#This needs to reference from the Palmer_SSDPlot code

```{r}

BestCost= c()# This is going to be our cost storage

BestCost= BestCost*100

Varx = rep(c(1,2,3), times = 6)

for(i in 1:length(patlist)){ #Going through the list of patients (1-6)
  for(j in 1:length(codonlist)){ #Going through the list of codon (3)
    pat = patlist[i] #saving the current patient in pat
    codon= codonlist[j] #saving the current codon 
    
    ssd_pat <- subset(EstCost_DF, Pat== pat, select = c(Pat, SSD, Cost, Codon))

    ssd_pat_Codon <- subset(ssd_pat, Codon== codon, select = c(Pat, SSD, Cost, Codon)) 
    index= which.min(ssd_pat_Codon$SSD) #This find the smallest ssd, the lower the ssd the, better the fit is
    BestCost= append(BestCost, ssd_pat_Codon$Cost[index])
    
  }
}

BestCodon = rep(c("AAC","AAT","TGT"), times = 6)

plot(Varx, BestCost, type= "p", col= "black", main=paste("Best Estimated Guess"), xlab="Codon", ylab= "Estimated Cost", xaxt="n")
axis(1,labels = codonlist, at = c(1, 2, 3),las=1)

```

```{r}
library(ggplot2)
#pdf("../Plots/Palmer_SummaryPlot/patsum2.pdf",width = 10, height =10)
ggplot(data.frame(x=BestCodon, y=log(BestCost)), aes(BestCodon, log(BestCost), colour = BestCodon)) + geom_point(size = 2) + geom_count()+ggtitle("Estimate the Fitness Cost of K103N and Y181C") +
  xlab("Codon") + ylab("Percentage of Fitness Cost")
#dev.off()
```